### ISSUE TITLE
а как устанавливать-то?

### ISSUE THREAD

**Issue by shredder2003** [dreadatour/pidgin-mra#1]
ildar@ildar ~/Загрузки/dreadatour-pidgin-mra-b886b72 $ make
gcc -I/usr/include/libpurple -DPURPLE_PLUGINS -DENABLE_NLS -Wall -Wextra -pthread -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include -I. -g -O2 -pipe src/mra_net.c src/libmra.c -o libmra.so -shared -fPIC -DPIC
In file included from src/mra_net.c:22:
src/libmra.h:38:18: error: glib.h: No such file or directory
src/libmra.h:42:24: error: glib/gi18n.h: No such file or directory
src/libmra.h:45:19: error: proxy.h: No such file or directory
src/libmra.h:46:21: error: sslconn.h: No such file or directory
src/libmra.h:47:18: error: prpl.h: No such file or directory
src/libmra.h:48:19: error: debug.h: No such file or directory
src/libmra.h:49:24: error: connection.h: No such file or directory
src/libmra.h:50:21: error: request.h: No such file or directory
src/libmra.h:51:22: error: dnsquery.h: No such file or directory

Понятно, что нужно какие-то исходники тоже иметь.. пидгиновские, что ли..
куда папку с установкой копировать, что за исходники должны быть, надо бы написать, а то убунтоводов много ведь :)

**Comment by dreadatour** [comment]
Попробуйте поставить пакет pidgin-dev:
$ sudo apt-get install pidgin-dev

а дальше - как обычно:
$ make  
$ sudo make install

Чуть позже я сделаю deb-пакет, а так же нормальный configure для плагина =)

**Comment by shredder2003** [comment]
клёво!!!
на форумах раскидай объявление, что плагин есть.
особенно на убунту.ру :)

**Comment by shredder2003** [comment]
работает
