### ISSUE TITLE
Компиляция по Windows

### ISSUE THREAD

**Issue by SVilgelm** [dreadatour/pidgin-mra#15]
Может кто-нибудь описать как скомпилировать под windows?

**Comment by dreadatour** [comment]
К сожалению, у меня нет Windows нигде под рукой - я даже примерно не смогу подсказать, как это компилировать =(

**Comment by dreadatour** [comment]
Если кто-нибудь опишет - я буду рад добавить инфу и DLL сюда =)

**Comment by LexLiven** [comment]
# Поставил Dev C++ и Cygwin. Пробую.

Попробовал. Очень много зависимостей от чисто линуксовых библиотек. поставил их в cygwin - видимо, сами эти библиотеки отказываются компилиться.
Одно из сообщений:

In file included from c:/cygwin/usr/include/asm/socket.h:14,
                 from c:/cygwin/usr/include/cygwin/socket.h:48,
                 from c:/cygwin/usr/include/cygwin/in.h:21,
                 from c:/cygwin/usr/include/netinet/in.h:14,
                 from c:/cygwin/usr/include/arpa/inet.h:14,
                 from E:\make\src\/libmra.h:54,
                 from E:\make\src\libmra.c:24:
c:/cygwin/usr/include/cygwin/if.h:106: error: syntax error before "caddr_t"
c:/cygwin/usr/include/cygwin/if.h:106: warning: no semicolon at end of struct or union
c:/cygwin/usr/include/cygwin/if.h:106: warning: no semicolon at end of struct or union
c:/cygwin/usr/include/cygwin/if.h:108: error: syntax error before '}' token
c:/cygwin/usr/include/cygwin/if.h:108: warning: data definition has no type or storage class

c:/cygwin/usr/include/cygwin/if.h:109: error: syntax error before '}' token
