### ISSUE TITLE
Все контакты оффлайн.

### ISSUE THREAD

**Issue by freemandigger** [dreadatour/pidgin-mra#16]
После авторизации ничего не происходит - все отображаются будто бы оффлайн, но с теми кто на самом деле онлайн общение проходит нормально.
# pidgin -v

Pidgin 2.7.9 (libpurple 2.7.9)
# uname -a

Linux xxx 2.6.35-26-generic #46-Ubuntu SMP Sun Jan 30 06:59:07 UTC 2011 x86_64 GNU/Linux

(K)Ubuntu 10.10

**Comment by Kerb** [comment]
В libmra.h  нужно заменить следующие строчки на указанные

<pre>
#define MRA_STATUS_ID_OFFLINE           "offline"
#define MRA_STATUS_ID_ONLINE            "available"
#define MRA_STATUS_ID_AWAY              "away"
#define MRA_STATUS_ID_UNDETERMINATED    "unset"
#define MRA_STATUS_ID_INVISIBLE         "invisible"
</pre>


затем пересобрать библиотеку: 

<pre>
make clean
make
sudo make install
</pre>

**Comment by freemandigger** [comment]
Отлично, спасибо!
Так гораздо лучше :)
