### ISSUE TITLE
Проблемы с установкой в Debian

### ISSUE THREAD

**Issue by LexLiven** [dreadatour/pidgin-mra#17]
Ребята, а как установить плагин под дебианом?
В системе Пиджин 2.4. Плагин требует 2.6. На сайте пиджина - есть 2.7, но только не под дебиан. Из исходников оттуда не компилится... Выход есть?

**Comment by dreadatour** [comment]
Как вариант - воспользоваться способом, описанным здесь: http://libc6.org/page/ustanovka-pidgin-262-v-debian-5-lenny/

**Comment by LexLiven** [comment]
он при этом хочет снести гнома...

**Comment by LexLiven** [comment]
черт... закрыл случайно...

**Comment by dreadatour** [comment]
а что говорит установка из исходников? какие ошибки?

**Comment by LexLiven** [comment]
говорит, "не найден GLib 2.12. или установи мне pkg-config, чтобы я его видел"
и то, и другое стоят
