### ISSUE TITLE
При запуске вылетает Pidgin

### ISSUE THREAD

**Issue by LexLiven** [dreadatour/pidgin-mra#2]
Debian 5.0, Pidgin 2.4.3
Скачал, установил... Модуль определился в Пиджине, но когда настроил учетную запись - Пиджин виснет и вылетает. Если нужны какие-то логи, напишите, плиз, где их найти - я в линуксе новичок.

**Comment by dreadatour** [comment]
Добрый день!

Можно запустить пиджин в консоли вот такой командой:
pidgin -d | grep ' mra: '
Но в выводе будут присутствовать Ваши личные данные (логин/пароль) - плагин пока только тестируется и они могут быть полезны. Вы можете скопировать несколько последних строк (там будет информация о том, почему вылетает пиджин), которые не содержат личные данные, или же можно просто создать временный аккаунт - данные от которого не жалко опубликовать =)

(в ближайшее время - сегодня вечером - я уберу вывод личных данных в логи)

Спасибо за сообщение! =)

С уважением, Владимир.

**Comment by LexLiven** [comment]
1 попытка с этими параметрами
lex@debian:~$ pidgin -d|grep 'mra:'
(15:24:57) mra: == plugin_init ==
(15:24:57) mra: == plugin_load ==
(15:25:00) mra: == mra_list_icon ==
(15:25:21) mra: == mra_statuses ==
(15:25:21) mra: == mra_list_icon ==
(15:25:21) mra: == mra_list_icon ==
(15:25:21) mra: == mra_login ==
(15:25:21) mra: [mra_login] Try to connect to server
(15:25:27) mra: == mra_connect_cb ==
(15:25:27) mra: == mra_email_is_valid ==
(15:25:27) mra: [mra_email_is_valid] check email '*****************_'
(15:25:27) mra: [mra_email_is_valid] failed check 'allowed symbols'
(15:25:27) mra: [mra_connect_cb] email '**_*************_**' is invalid
(15:25:27) mra: == mra_list_icon ==
(15:25:27) mra: == mra_close ==
*_\* glibc detected **\* pidgin: double free or corruption (fasttop): 0x0839c700 ***

# И после этого он и висит... то есть, я правильно понял - плагин проверяет валидность адреса, но при ошибке - ничего не возвращает?

P.S.: адрес был записан с прописной буквы, остальные строчные. запись - полная, с "@mail.ru".
Я еще попробую позапускать с другими написаниями адреса и, в случае, если результаты будут отличаться - напишу еще.

**Comment by dreadatour** [comment]
Да, Вы правы, плагин проверяет валидность адреса. И это довольно странно, что он вылетает. Сегодня вечером я устраню этот баг =)

Попробуйте пока написать email полностью строчными буквами, а так же проследите за тем, чтобы не было пробелов в строке (пока не могу сказать, на что именно ругается плагин).

С уважением, Владимир.

**Comment by LexLiven** [comment]
При второй попытке он выдал тот же текст, но дописал

Pidgin 2.4.3 has segfaulted and attempted to dump a core file.
This is a bug in the software and has happened through
no fault of your own.

If you can reproduce the crash, please notify the developers
by reporting a bug at:
http://developer.pidgin.im/simpleticket/

Please make sure to specify what you were doing at the time
and post the backtrace from the core file.  If you do not know
how to get the backtrace, please read the instructions at
http://developer.pidgin.im/wiki/GetABacktrace

If you need further assistance, please IM either SeanEgn or 
LSchiere (via AIM).  Contact information for Sean and Luke 
on other protocols is at
http://developer.pidgin.im/wiki/DeveloperPages

и вылетел.

**Comment by LexLiven** [comment]
1. запуск с полностью строчным адресом...
   плагин загрузился успешно, получил список контактов
   потом:
   (15:53:52) mra: [mra_contact_list_cb] user хххххххх@mail.ru (23)
   (15:53:52) mra: [mra_contact_list_cb] group Друзья
   (15:53:52) mra: [mra_contact_list_cb] buddy хххххххх@mail.ru
   (15:53:52) mra: == mra_list_icon ==
   (15:53:52) mra: == mra_list_icon ==
   (15:53:52) mra: == mra_list_icon ==
   (15:53:52) mra: == mra_list_icon ==
   (15:53:52) mra: == mra_contact_set_status ==
   (15:53:52) mra: [mra_contact_set_status] хххххххх@mail.ru status: 0x00000000
   (15:53:52) mra: [mra_contact_set_status] хххххххх@mail.ru status is offline
   (15:53:52) mra: == mra_list_icon ==
   (15:53:52) mra: == mra_list_icon ==
   (15:53:52) mra: [mra_contact_list_cb] user phone (24)

и снова сообщение об ошибке Пиджина...
кстати, у меня в контактах нет пользователя "phone"

**Comment by LexLiven** [comment]
Так! Локализовал проблему.
Пользователя, действительно, нет. Но есть группа "Телефонные контакты". Как только я ее очистил (под виндой) - плагин загрузился и работает без проблем.

**Comment by dreadatour** [comment]
Понял! Сейчас буду фиксить )

**Comment by dreadatour** [comment]
Пофиксил =)

**Comment by eagafonov** [comment]
Привет!

Буду некропостером, но бага всё ещё есть ;-)

Проблема в том,  что в функции mra_connect_cb поле mmp->connect_data не сбрасывется в NULL, если мыло невалидное (в libmra.c:650 выходт по return). Краш происходит в mra_close в libmra.c:1084, внутри purple_proxy_connect_cancel. К этому моменту соединение установлено  (mra_connect_cb уже вызвался!!!) и дёргать purple_proxy_connect_cancel не надо.

Пофикстить можно двумя способами: перенести mmp->connect_data=NULL в начало mra_connect_cb, либо прорверять валидность мыла ДО установки соединения. 

Я поробовал первый способ (краша нет), но второй более правильный IMHO.
скоро будет патч.

**Comment by eagafonov** [comment]
Патч 
https://github.com/eagafonov/pidgin-mra/commit/df192421a8accf3807dab1629f3634a237932616
