### ISSUE TITLE
Список игнорируемых пользователей.

### ISSUE THREAD

**Issue by LexLiven** [dreadatour/pidgin-mra#4]
Плагин вылетает, убивая Pidgin, как только натыкается на пользователя, который занесен в список игнорируемых. Сразу.
(17:22:39) mra: [mra_contact_list_cb] user ignored_user@mail.ru (36)

**Comment by dreadatour** [comment]
Хм... Спасибо, сейчас буду фиксить =)

**Comment by dreadatour** [comment]
Пофиксил.
