### ISSUE TITLE
Падение pidgin'а при обрыве связи (переход в ждущий режим и восстановление)

### ISSUE THREAD

**Issue by my2coins** [dreadatour/pidgin-mra#7]
Выдержка из сообщений pidgin:

dns[9230] Error: getaddrinfo returned -2
(00:32:08) dns: Created new DNS child 9233, there are now 3 children.
(00:32:08) dns: Successfully sent DNS request to child 9233
(00:32:08) network: Got StateChange from NetworkManager: 4.
(00:32:08) account: Disconnecting account 42122507 (0x8323a28)
(00:32:08) connection: Disconnecting connection 0x9525240
(00:32:08) oscar: Destroying oscar connection of type 0x0017.  Disconnect reason is 0
(00:32:08) oscar: Disconnected.  Code is 0x0000 and msg is 
(00:32:08) oscar: Signed off.
dns[9233] Error: getaddrinfo returned -2
(00:32:08) mra: == mra_list_icon ==
(00:32:08) connection: Destroying connection 0x9525240
(00:32:08) account: Disconnecting account XXXXXX@livejournal.com/NBook (0x840a1a8)
(00:32:08) connection: Disconnecting connection 0x9f90d30
(00:32:08) mra: == mra_list_icon ==
(00:32:08) connection: Destroying connection 0x9f90d30
(00:32:08) account: Disconnecting account XXXXXX@ya.ru/T (0x83f1c88)
(00:32:08) connection: Disconnecting connection 0x93dc980
(00:32:08) mra: == mra_list_icon ==
(00:32:08) connection: Destroying connection 0x93dc980
(00:32:08) account: Disconnecting account XXXXXX@gmail.com/ (0x83f43b8)
(00:32:08) connection: Disconnecting connection 0x9497cf8
(00:32:08) mra: == mra_list_icon ==
(00:32:08) connection: Destroying connection 0x9497cf8
(00:32:08) account: Disconnecting account my2coins@mail.ru (0x83f9a60)
(00:32:08) connection: Disconnecting connection 0x94d5e90
(00:32:08) mra: == mra_close ==
**\* glibc detected **\* pidgin: free(): invalid pointer: 0x086d60e8 ***

Количество вызовов mra_list_icon не очень понятно, возможно, стоило бы уменьшить. Но падение не в нём, падение в mra_close. Где-то покоробился указатель по дороге.

**Comment by dreadatour** [comment]
Fixed =) Спасибо!!

**Comment by my2coins** [comment]
поздравляю ) пакуй уже 0.2, что ли )

**Comment by dreadatour** [comment]
Ещё хочу пару багов исправить до 0.2 =)
