### ISSUE TITLE
Не соединяется в Linux 64 bit

### ISSUE THREAD

**Issue by alexbo** [dreadatour/pidgin-mra#9]
Установленная система (uname -a):
Linux ASAP 2.6.31-20-generic #58-Ubuntu SMP Fri Mar 12 04:38:19 UTC 2010 x86_64 GNU/Linux

Pidgin 2.6.2. Код плагина от 21 апреля.

В логе пишут, что:
(14:42:50) mra: == plugin_init ==
(14:42:50) mra: == plugin_load ==
(14:42:50) mra: == mra_statuses ==
(14:42:50) mra: == mra_login ==
(14:42:50) mra: [mra_login] Try to connect to server
(14:42:50) mra: == mra_connect_cb ==
(14:42:50) mra: == mra_email_is_valid ==
(14:42:50) mra: [mra_email_is_valid] check email 'xxxxxxxxxxxxxxxxxxxx@mail.ru'
(14:42:50) mra: == mra_actions ==
(14:42:50) mra: [mra_connect_cb] Connected
(14:42:50) mra: [mra_connect_cb] Trying to login user...
(14:42:50) mra: == mra_net_send_hello ==
(14:42:50) mra: == mra_net_fill_cs_header ==
(14:42:50) mra: == mra_net_send ==
(14:42:50) mra: == mra_net_send_flush ==
(14:42:50) mra: [mra_net_send_flush] bytes sent: 72
(14:42:50) mra: send: deadbeef-00000000-00010008-00000000-00000000-00000000-00001001 000000000000000000000000c49be526ae7f0000b0f9a60100000000
(14:42:51) mra: == mra_net_read_cb ==
(14:42:51) mra: [mra_net_read_cb] bytes readed: 0
(14:42:51) mra: read: error
(14:42:51) mra: == mra_net_read_cb ==
(14:42:51) mra: [mra_net_read_cb] bytes readed: 0
(14:42:51) mra: read: error
(14:42:51) mra: == mra_close ==
(14:42:51) mra: [mra_close] connection was closed

**Comment by 6uest** [comment]
Сборка из исходников от Суббота, Сентябрь 18 2010 работает на Ubuntu 10.10 amd64. Оповещения о новой почте тоже работают.

**Comment by 6uest** [comment]
хотя нет, вру. Заработало только в первый раз почему-то. При последующем запуске выдаёт: Ошибка сегментирования (core dumped)

'
(23:51:14) util: parsed 3787
(23:51:14) mra: == mra_load_avatar_cb ==
(23:51:14) mra: [mra_load_avatar_cb] downloaded avatar for user xxx@corp.mail.ru
(23:51:14) mra: [mra_load_avatar_cb] downloaded: 3787 bytes
(23:51:14) mra: == mra_list_emblem ==
(23:51:14) mra: [mra_list_emblem] get xxx@corp.mail.ru emblem: TRUE, id: 44
(23:51:14) mra: == mra_status_text ==
(23:51:14) proxy: Connecting to obraz.foto.mail.ru:80.
(23:51:14) proxy: Connected to obraz.foto.mail.ru:80.
(23:51:14) util: request constructed
(23:51:14) dns: Got response for 'obraz.foto.mail.ru'
(23:51:14) dnsquery: IP resolved for obraz.foto.mail.ru
(23:51:14) proxy: Attempting connection to 94.100.186.198
(23:51:14) proxy: Connecting to obraz.foto.mail.ru:80 with no proxy
(23:51:14) proxy: Connection in progress
(23:51:14) dns: Successfully sent DNS request to child 5923
(23:51:14) util: Response headers: 'HTTP/1.1 200 OK
Date: Sat, 18 Sep 2010 19:51:14 GMT
Server: Apache/1.3.27 (Unix) mru_xml/0.471 gorgona/2.1 mod_jk/1.2.4 mod_ruby/1.0.7 Ruby/1.6.8 mod_mrim/0.17
Connection: close
Cache-Control: max-age=604800
Last-Modified: Tue, 02 Feb 2010 15:31:44 GMT
Expires: Sat, 25 Sep 2010 19:51:14 GMT
Content-Length: 2337
Content-Type: image/jpeg

'
(23:51:14) util: parsed 2337
(23:51:14) mra: == mra_load_avatar_cb ==
dns[5924]: Oops, father has gone, wait for me, wait...!
Ошибка сегментирования (core dumped)
dns[5923]: Oops, father has gone, wait for me, wait...!
dns[5922]: Oops, father has gone, wait for me, wait...!
dns[5840]: Oops, father has gone, wait for me, wait...!

**Comment by dreadatour** [comment]
Проблема актуальна? =)))

**Comment by alexbo** [comment]
Перешел на 32-битный Линукс, так что проблема не актуальна для меня. Спасибо, что не забыли :-)
